// Schaetzfragen: q = Frage, a = Antwort, unit = Einheit fuer die Anzeige.
// Punkte gibt es nach dem Verhaeltnis zur richtigen Zahl (Faktor 2 daneben
// gibt noch Punkte), also taugen auch grosse Zahlen. Nur feste Werte.
// tol: absolute Toleranz statt Verhaeltnis (fuer Jahreszahlen).
module.exports = [
    { q: 'How tall is the Eiffel Tower (with antennas)?', a: 330, unit: 'm' },
    { q: 'How tall is Mount Everest?', a: 8849, unit: 'm' },
    { q: 'How tall is the Burj Khalifa?', a: 828, unit: 'm' },
    { q: 'How tall is the Statue of Liberty (ground to torch)?', a: 93, unit: 'm' },
    { q: 'How tall is the Great Pyramid of Giza today?', a: 139, unit: 'm' },
    { q: 'How tall is the Leaning Tower of Pisa?', a: 56, unit: 'm' },
    { q: 'How tall is the Berlin TV Tower (Fernsehturm)?', a: 368, unit: 'm' },
    { q: 'How tall is Big Ben\'s tower (Elizabeth Tower)?', a: 96, unit: 'm' },
    { q: 'How tall is an adult giraffe (male), roughly?', a: 5.5, unit: 'm' },
    { q: 'How long is a blue whale (large adult)?', a: 30, unit: 'm' },
    { q: 'How long is a standard football (soccer) pitch in big stadiums?', a: 105, unit: 'm' },
    { q: 'How high is a basketball hoop?', a: 3.05, unit: 'm' },
    { q: 'How long is the Golden Gate Bridge (total)?', a: 2737, unit: 'm' },
    { q: 'How long is the Great Wall of China (all branches)?', a: 21196, unit: 'km' },
    { q: 'How long is the river Nile?', a: 6650, unit: 'km' },
    { q: 'How long is the river Rhine?', a: 1233, unit: 'km' },
    { q: 'How far is the Moon from Earth (average)?', a: 384400, unit: 'km' },
    { q: 'How far is the Sun from Earth (average)?', a: 149.6, unit: 'million km' },
    { q: 'What is the diameter of the Earth?', a: 12742, unit: 'km' },
    { q: 'What is the circumference of the Earth at the equator?', a: 40075, unit: 'km' },
    { q: 'How deep is the Mariana Trench (deepest point)?', a: 10935, unit: 'm' },
    { q: 'How many kilometres is it from Berlin to Munich (straight line)?', a: 504, unit: 'km' },
    { q: 'How many kilometres is it from London to New York (straight line)?', a: 5570, unit: 'km' },
    { q: 'How many countries are members of the United Nations?', a: 193, unit: 'countries' },
    { q: 'How many bones are in the human body?', a: 206, unit: 'bones' },
    { q: 'How many keys does a standard piano have?', a: 88, unit: 'keys' },
    { q: 'How many days does it take Mars to orbit the Sun?', a: 687, unit: 'days' },
    { q: 'How many moons of Mars are there?', a: 2, unit: 'moons' },
    { q: 'How hot is the surface of the Sun?', a: 5500, unit: '°C' },
    { q: 'At what temperature does iron melt?', a: 1538, unit: '°C' },
    { q: 'What is the top speed of a cheetah?', a: 110, unit: 'km/h' },
    { q: 'How fast does sound travel in air (20 °C)?', a: 343, unit: 'm/s' },
    { q: 'How heavy is an adult African elephant (male), roughly?', a: 6000, unit: 'kg' },
    { q: 'How heavy is a blue whale (large adult)?', a: 150000, unit: 'kg' },
    { q: 'How much does a standard LEGO 2×4 brick weigh?', a: 2.3, unit: 'g' },
    { q: 'How heavy is a football (soccer ball), standard size 5?', a: 430, unit: 'g' },
    { q: 'How many litres of blood does an adult human have?', a: 5, unit: 'litres' },
    { q: 'How many hours does a sloth sleep per day in the wild, roughly?', a: 10, unit: 'hours' },
    { q: 'How many years does a Galápagos tortoise live, up to about?', a: 150, unit: 'years' },
    { q: 'How many seconds are in a day?', a: 86400, unit: 'seconds' },
    { q: 'How many people live in Germany, roughly?', a: 84, unit: 'million' },
    { q: 'How many people live on Earth, roughly?', a: 8, unit: 'billion' },
    { q: 'In what year was the first iPhone released?', a: 2007, unit: '(year)', tol: 10 },
    { q: 'In what year was the Eiffel Tower completed?', a: 1889, unit: '(year)', tol: 40 },
    { q: 'In what year did Columbus first reach the Americas?', a: 1492, unit: '(year)', tol: 60 },
    { q: 'How long is a marathon exactly?', a: 42195, unit: 'm' },
    { q: 'How many squares does a Rubik\'s Cube show on all sides together?', a: 54, unit: 'squares' },
    { q: 'How many Minecraft blocks tall is the default world height (1.18+, from bottom to top)?', a: 384, unit: 'blocks' },
    { q: 'How many cards are in a standard deck (without jokers)?', a: 52, unit: 'cards' },
    { q: 'How many numbers are on a European roulette wheel (incl. 0)?', a: 37, unit: 'numbers' },
    { q: 'How many ribs does a human have?', a: 24, unit: 'ribs' },
    { q: 'How wide is the Strait of Gibraltar at its narrowest?', a: 14, unit: 'km' },
    { q: 'How long is the Panama Canal?', a: 82, unit: 'km' },
    { q: 'How tall is an average beagle at the shoulder?', a: 38, unit: 'cm' }
];
