// Orte fuer das Geo-Event: "Where is ...?" – man klickt auf die Weltkarte.
// Koordinaten auf ~0,1 Grad genau, das reicht bei einer Karte, auf der ein
// Pixel eher 50 km sind.
module.exports = [
    { name: 'Tokyo', hint: 'Japan', lat: 35.7, lon: 139.7 },
    { name: 'New York City', hint: 'USA', lat: 40.7, lon: -74.0 },
    { name: 'London', hint: 'United Kingdom', lat: 51.5, lon: -0.1 },
    { name: 'Paris', hint: 'France', lat: 48.9, lon: 2.35 },
    { name: 'Berlin', hint: 'Germany', lat: 52.5, lon: 13.4 },
    { name: 'Moscow', hint: 'Russia', lat: 55.75, lon: 37.6 },
    { name: 'Sydney', hint: 'Australia', lat: -33.9, lon: 151.2 },
    { name: 'Rio de Janeiro', hint: 'Brazil', lat: -22.9, lon: -43.2 },
    { name: 'Cairo', hint: 'Egypt', lat: 30.0, lon: 31.2 },
    { name: 'Cape Town', hint: 'South Africa', lat: -33.9, lon: 18.4 },
    { name: 'Mumbai', hint: 'India', lat: 19.1, lon: 72.9 },
    { name: 'Beijing', hint: 'China', lat: 39.9, lon: 116.4 },
    { name: 'Los Angeles', hint: 'USA', lat: 34.05, lon: -118.25 },
    { name: 'Mexico City', hint: 'Mexico', lat: 19.4, lon: -99.1 },
    { name: 'Buenos Aires', hint: 'Argentina', lat: -34.6, lon: -58.4 },
    { name: 'Istanbul', hint: 'Turkey', lat: 41.0, lon: 29.0 },
    { name: 'Dubai', hint: 'UAE', lat: 25.2, lon: 55.3 },
    { name: 'Singapore', hint: 'Singapore', lat: 1.35, lon: 103.8 },
    { name: 'Bangkok', hint: 'Thailand', lat: 13.75, lon: 100.5 },
    { name: 'Seoul', hint: 'South Korea', lat: 37.55, lon: 127.0 },
    { name: 'Reykjavík', hint: 'Iceland', lat: 64.15, lon: -21.9 },
    { name: 'Oslo', hint: 'Norway', lat: 59.9, lon: 10.75 },
    { name: 'Stockholm', hint: 'Sweden', lat: 59.3, lon: 18.1 },
    { name: 'Helsinki', hint: 'Finland', lat: 60.2, lon: 24.9 },
    { name: 'Madrid', hint: 'Spain', lat: 40.4, lon: -3.7 },
    { name: 'Lisbon', hint: 'Portugal', lat: 38.7, lon: -9.1 },
    { name: 'Rome', hint: 'Italy', lat: 41.9, lon: 12.5 },
    { name: 'Athens', hint: 'Greece', lat: 37.98, lon: 23.7 },
    { name: 'Vienna', hint: 'Austria', lat: 48.2, lon: 16.4 },
    { name: 'Warsaw', hint: 'Poland', lat: 52.2, lon: 21.0 },
    { name: 'Kyiv', hint: 'Ukraine', lat: 50.45, lon: 30.5 },
    { name: 'Amsterdam', hint: 'Netherlands', lat: 52.4, lon: 4.9 },
    { name: 'Dublin', hint: 'Ireland', lat: 53.35, lon: -6.25 },
    { name: 'Edinburgh', hint: 'Scotland', lat: 55.95, lon: -3.2 },
    { name: 'Nairobi', hint: 'Kenya', lat: -1.3, lon: 36.8 },
    { name: 'Lagos', hint: 'Nigeria', lat: 6.5, lon: 3.4 },
    { name: 'Marrakesh', hint: 'Morocco', lat: 31.6, lon: -8.0 },
    { name: 'Addis Ababa', hint: 'Ethiopia', lat: 9.0, lon: 38.75 },
    { name: 'Madagascar', hint: 'Island country', lat: -19.0, lon: 46.9 },
    { name: 'Toronto', hint: 'Canada', lat: 43.65, lon: -79.4 },
    { name: 'Vancouver', hint: 'Canada', lat: 49.3, lon: -123.1 },
    { name: 'Chicago', hint: 'USA', lat: 41.9, lon: -87.6 },
    { name: 'Miami', hint: 'USA', lat: 25.8, lon: -80.2 },
    { name: 'Anchorage', hint: 'Alaska, USA', lat: 61.2, lon: -149.9 },
    { name: 'Honolulu', hint: 'Hawaii, USA', lat: 21.3, lon: -157.85 },
    { name: 'Havana', hint: 'Cuba', lat: 23.1, lon: -82.4 },
    { name: 'Lima', hint: 'Peru', lat: -12.05, lon: -77.05 },
    { name: 'Santiago', hint: 'Chile', lat: -33.45, lon: -70.65 },
    { name: 'Bogotá', hint: 'Colombia', lat: 4.7, lon: -74.1 },
    { name: 'Manaus', hint: 'Amazon, Brazil', lat: -3.1, lon: -60.0 },
    { name: 'Ushuaia', hint: 'Argentina', lat: -54.8, lon: -68.3 },
    { name: 'Auckland', hint: 'New Zealand', lat: -36.85, lon: 174.75 },
    { name: 'Perth', hint: 'Australia', lat: -31.95, lon: 115.85 },
    { name: 'Jakarta', hint: 'Indonesia', lat: -6.2, lon: 106.85 },
    { name: 'Manila', hint: 'Philippines', lat: 14.6, lon: 121.0 },
    { name: 'Hanoi', hint: 'Vietnam', lat: 21.0, lon: 105.85 },
    { name: 'Kathmandu', hint: 'Nepal', lat: 27.7, lon: 85.3 },
    { name: 'Tehran', hint: 'Iran', lat: 35.7, lon: 51.4 },
    { name: 'Riyadh', hint: 'Saudi Arabia', lat: 24.7, lon: 46.7 },
    { name: 'Jerusalem', hint: 'Middle East', lat: 31.8, lon: 35.2 },
    { name: 'Ulaanbaatar', hint: 'Mongolia', lat: 47.9, lon: 106.9 },
    { name: 'Vladivostok', hint: 'Russia', lat: 43.1, lon: 131.9 },
    { name: 'Novosibirsk', hint: 'Russia', lat: 55.0, lon: 82.9 },
    { name: 'Hong Kong', hint: 'China', lat: 22.3, lon: 114.2 },
    { name: 'Shanghai', hint: 'China', lat: 31.2, lon: 121.5 },
    { name: 'Taipei', hint: 'Taiwan', lat: 25.05, lon: 121.55 },
    { name: 'Karachi', hint: 'Pakistan', lat: 24.85, lon: 67.0 },
    { name: 'Colombo', hint: 'Sri Lanka', lat: 6.9, lon: 79.85 },
    { name: 'Eiffel Tower', hint: 'Landmark', lat: 48.86, lon: 2.29 },
    { name: 'Statue of Liberty', hint: 'Landmark', lat: 40.69, lon: -74.04 },
    { name: 'Great Pyramid of Giza', hint: 'Landmark', lat: 29.98, lon: 31.13 },
    { name: 'Machu Picchu', hint: 'Landmark', lat: -13.16, lon: -72.55 },
    { name: 'Taj Mahal', hint: 'Landmark', lat: 27.17, lon: 78.04 },
    { name: 'Mount Everest', hint: 'Mountain', lat: 27.99, lon: 86.93 },
    { name: 'Mount Kilimanjaro', hint: 'Mountain', lat: -3.07, lon: 37.35 },
    { name: 'Grand Canyon', hint: 'Landmark', lat: 36.1, lon: -112.1 },
    { name: 'Niagara Falls', hint: 'Waterfall', lat: 43.08, lon: -79.07 },
    { name: 'Uluru', hint: 'Landmark', lat: -25.34, lon: 131.04 },
    { name: 'Angkor Wat', hint: 'Landmark', lat: 13.41, lon: 103.87 },
    { name: 'Christ the Redeemer', hint: 'Landmark', lat: -22.95, lon: -43.21 },
    { name: 'Petra', hint: 'Landmark', lat: 30.33, lon: 35.44 },
    { name: 'Chichén Itzá', hint: 'Landmark', lat: 20.68, lon: -88.57 },
    { name: 'Stonehenge', hint: 'Landmark', lat: 51.18, lon: -1.83 },
    { name: 'Neuschwanstein Castle', hint: 'Landmark', lat: 47.56, lon: 10.75 },
    { name: 'Great Barrier Reef', hint: 'Nature', lat: -18.3, lon: 147.7 },
    { name: 'Victoria Falls', hint: 'Waterfall', lat: -17.92, lon: 25.86 },
    { name: 'Easter Island', hint: 'Island', lat: -27.1, lon: -109.35 },
    { name: 'Galápagos Islands', hint: 'Islands', lat: -0.8, lon: -91.0 },
    { name: 'Svalbard', hint: 'Arctic', lat: 78.2, lon: 15.6 },
    { name: 'North Pole', hint: 'Arctic', lat: 90, lon: 0 },
    { name: 'Mount Fuji', hint: 'Mountain', lat: 35.36, lon: 138.73 },
    { name: 'Dead Sea', hint: 'Lake', lat: 31.5, lon: 35.5 },
    { name: 'Lake Baikal', hint: 'Lake', lat: 53.5, lon: 108.0 },
    { name: 'Sahara (centre)', hint: 'Desert', lat: 23.4, lon: 12.0 },
    { name: 'Hawaii Big Island', hint: 'Island', lat: 19.6, lon: -155.5 },
    { name: 'Tasmania', hint: 'Island', lat: -42.0, lon: 146.6 },
    { name: 'Greenland (centre)', hint: 'Island', lat: 72.0, lon: -40.0 },
    { name: 'Bermuda', hint: 'Island', lat: 32.3, lon: -64.8 },
    { name: 'Las Vegas', hint: 'USA', lat: 36.17, lon: -115.14 },
    { name: 'Monaco', hint: 'Microstate', lat: 43.74, lon: 7.42 },
    { name: 'Venice', hint: 'Italy', lat: 45.44, lon: 12.33 }
];
