// Fragen fuer das Trivia-Event: q = Frage, a = richtige Antwort, w = drei falsche.
// Die Oberflaeche ist englisch, also auch die Fragen. Nur Dinge, die sich nicht
// aendern (keine "aktueller Rekord"- oder "wer ist gerade"-Fragen).
module.exports = [
    { q: 'What is the largest planet in our solar system?', a: 'Jupiter', w: ['Saturn', 'Neptune', 'Earth'] },
    { q: 'Which planet is known as the Red Planet?', a: 'Mars', w: ['Venus', 'Mercury', 'Jupiter'] },
    { q: 'How many legs does a spider have?', a: '8', w: ['6', '10', '12'] },
    { q: 'What is the chemical symbol for gold?', a: 'Au', w: ['Ag', 'Go', 'Gd'] },
    { q: 'What is the chemical symbol for iron?', a: 'Fe', w: ['Ir', 'In', 'I'] },
    { q: 'What gas do plants absorb from the air?', a: 'Carbon dioxide', w: ['Oxygen', 'Nitrogen', 'Helium'] },
    { q: 'What is the hardest natural substance?', a: 'Diamond', w: ['Quartz', 'Iron', 'Granite'] },
    { q: 'How many bones does an adult human have?', a: '206', w: ['186', '226', '312'] },
    { q: 'What is the largest ocean on Earth?', a: 'Pacific', w: ['Atlantic', 'Indian', 'Arctic'] },
    { q: 'What is the capital of Australia?', a: 'Canberra', w: ['Sydney', 'Melbourne', 'Perth'] },
    { q: 'What is the capital of Canada?', a: 'Ottawa', w: ['Toronto', 'Vancouver', 'Montreal'] },
    { q: 'What is the capital of Japan?', a: 'Tokyo', w: ['Kyoto', 'Osaka', 'Hiroshima'] },
    { q: 'What is the capital of Brazil?', a: 'Brasília', w: ['Rio de Janeiro', 'São Paulo', 'Salvador'] },
    { q: 'What is the capital of Turkey?', a: 'Ankara', w: ['Istanbul', 'Izmir', 'Antalya'] },
    { q: 'What is the capital of Switzerland?', a: 'Bern', w: ['Zurich', 'Geneva', 'Basel'] },
    { q: 'Which country has the most people living in it?', a: 'India', w: ['USA', 'Russia', 'Indonesia'] },
    { q: 'Which is the longest river in Europe?', a: 'Volga', w: ['Danube', 'Rhine', 'Elbe'] },
    { q: 'Which is the largest desert in the world (hot or cold)?', a: 'Antarctica', w: ['Sahara', 'Gobi', 'Kalahari'] },
    { q: 'On which continent is Egypt?', a: 'Africa', w: ['Asia', 'Europe', 'South America'] },
    { q: 'What is the tallest mountain on Earth above sea level?', a: 'Mount Everest', w: ['K2', 'Kilimanjaro', 'Mont Blanc'] },
    { q: 'Which country is shaped like a boot?', a: 'Italy', w: ['Greece', 'Portugal', 'Chile'] },
    { q: 'How many continents are there (usual count)?', a: '7', w: ['5', '6', '8'] },
    { q: 'Who painted the Mona Lisa?', a: 'Leonardo da Vinci', w: ['Michelangelo', 'Raphael', 'Rembrandt'] },
    { q: 'Who painted "The Starry Night"?', a: 'Vincent van Gogh', w: ['Claude Monet', 'Pablo Picasso', 'Salvador Dalí'] },
    { q: 'Who wrote "Romeo and Juliet"?', a: 'William Shakespeare', w: ['Charles Dickens', 'Jane Austen', 'Mark Twain'] },
    { q: 'Who composed the "Moonlight Sonata"?', a: 'Beethoven', w: ['Mozart', 'Bach', 'Chopin'] },
    { q: 'In which year did the Titanic sink?', a: '1912', w: ['1905', '1921', '1898'] },
    { q: 'In which year did the Berlin Wall fall?', a: '1989', w: ['1991', '1985', '1979'] },
    { q: 'In which year did humans first land on the Moon?', a: '1969', w: ['1965', '1972', '1959'] },
    { q: 'Who was the first person to walk on the Moon?', a: 'Neil Armstrong', w: ['Buzz Aldrin', 'Yuri Gagarin', 'John Glenn'] },
    { q: 'Who was the first human in space?', a: 'Yuri Gagarin', w: ['Neil Armstrong', 'Alan Shepard', 'Valentina Tereshkova'] },
    { q: 'Which ancient wonder stood in Egypt and still exists?', a: 'Great Pyramid of Giza', w: ['Colossus of Rhodes', 'Hanging Gardens', 'Lighthouse of Alexandria'] },
    { q: 'What is the smallest prime number?', a: '2', w: ['1', '3', '0'] },
    { q: 'What is 12 × 12?', a: '144', w: ['124', '132', '154'] },
    { q: 'How many sides does a hexagon have?', a: '6', w: ['5', '7', '8'] },
    { q: 'What is the square root of 81?', a: '9', w: ['8', '7', '11'] },
    { q: 'How many minutes are in a day?', a: '1440', w: ['1200', '1600', '960'] },
    { q: 'What is the freezing point of water in Fahrenheit?', a: '32 °F', w: ['0 °F', '12 °F', '100 °F'] },
    { q: 'What is the boiling point of water at sea level in Celsius?', a: '100 °C', w: ['90 °C', '110 °C', '212 °C'] },
    { q: 'What is the largest mammal?', a: 'Blue whale', w: ['Elephant', 'Giraffe', 'Sperm whale'] },
    { q: 'What is the fastest land animal?', a: 'Cheetah', w: ['Lion', 'Pronghorn', 'Greyhound'] },
    { q: 'Which bird is known for being unable to fly and living in Antarctica?', a: 'Penguin', w: ['Ostrich', 'Kiwi', 'Emu'] },
    { q: 'How many hearts does an octopus have?', a: '3', w: ['1', '2', '8'] },
    { q: 'What do bees make?', a: 'Honey', w: ['Silk', 'Wax only', 'Milk'] },
    { q: 'Which animal is known as the "King of the Jungle"?', a: 'Lion', w: ['Tiger', 'Gorilla', 'Elephant'] },
    { q: 'What is a baby kangaroo called?', a: 'Joey', w: ['Kit', 'Cub', 'Calf'] },
    { q: 'What is the national animal of Scotland?', a: 'Unicorn', w: ['Lion', 'Red deer', 'Golden eagle'] },
    { q: 'Which fruit has its seeds on the outside?', a: 'Strawberry', w: ['Raspberry', 'Kiwi', 'Blueberry'] },
    { q: 'Which country invented pizza as we know it?', a: 'Italy', w: ['Greece', 'USA', 'France'] },
    { q: 'Which country is famous for the dish paella?', a: 'Spain', w: ['Mexico', 'Portugal', 'Italy'] },
    { q: 'What is the main ingredient of guacamole?', a: 'Avocado', w: ['Tomato', 'Pea', 'Lime'] },
    { q: 'Which vitamin do we get from sunlight?', a: 'Vitamin D', w: ['Vitamin C', 'Vitamin A', 'Vitamin B12'] },
    { q: 'How many players are on a football (soccer) team on the field?', a: '11', w: ['10', '9', '12'] },
    { q: 'How many rings are on the Olympic flag?', a: '5', w: ['4', '6', '7'] },
    { q: 'In which sport do you use a shuttlecock?', a: 'Badminton', w: ['Tennis', 'Squash', 'Table tennis'] },
    { q: 'How long is a marathon (km, rounded)?', a: '42 km', w: ['40 km', '45 km', '50 km'] },
    { q: 'In chess, which piece can only move diagonally?', a: 'Bishop', w: ['Rook', 'Knight', 'Queen'] },
    { q: 'How many squares are on a chessboard?', a: '64', w: ['60', '72', '81'] },
    { q: 'What is the maximum score in ten-pin bowling?', a: '300', w: ['250', '200', '360'] },
    { q: 'Which company makes the iPhone?', a: 'Apple', w: ['Samsung', 'Google', 'Nokia'] },
    { q: 'What does "CPU" stand for?', a: 'Central Processing Unit', w: ['Computer Power Unit', 'Central Program Utility', 'Core Processing Unit'] },
    { q: 'What does "HTML" stand for?', a: 'HyperText Markup Language', w: ['High Tech Modern Language', 'Hyperlink Text Mode Language', 'Home Tool Markup Language'] },
    { q: 'How many bits are in a byte?', a: '8', w: ['4', '16', '10'] },
    { q: 'Which programming language is named after a comedy group?', a: 'Python', w: ['Ruby', 'Java', 'Perl'] },
    { q: 'Which Nintendo handheld came out in 1989?', a: 'Game Boy', w: ['Nintendo DS', 'Game Boy Advance', 'Switch'] },
    { q: 'What is the name of the plumber in Nintendo games?', a: 'Mario', w: ['Luigi', 'Wario', 'Toad'] },
    { q: 'In Minecraft, what do you need to mine diamonds?', a: 'Iron pickaxe', w: ['Stone pickaxe', 'Wooden pickaxe', 'Gold pickaxe'] },
    { q: 'Which game features a battle bus?', a: 'Fortnite', w: ['PUBG', 'Apex Legends', 'Warzone'] },
    { q: 'What colour is Blinky, the ghost in Pac-Man?', a: 'Red', w: ['Pink', 'Cyan', 'Orange'] },
    { q: 'Which element has the atomic number 1?', a: 'Hydrogen', w: ['Helium', 'Oxygen', 'Carbon'] },
    { q: 'What is the speed of light, roughly?', a: '300,000 km/s', w: ['30,000 km/s', '3,000,000 km/s', '1,000 km/s'] },
    { q: 'Which planet has the most famous rings?', a: 'Saturn', w: ['Jupiter', 'Uranus', 'Neptune'] },
    { q: 'What is the closest star to Earth?', a: 'The Sun', w: ['Proxima Centauri', 'Sirius', 'Polaris'] },
    { q: 'How long does light from the Sun take to reach Earth?', a: 'About 8 minutes', w: ['About 8 seconds', 'About 1 hour', 'About 1 day'] },
    { q: 'What is the most spoken native language in the world?', a: 'Mandarin Chinese', w: ['English', 'Spanish', 'Hindi'] },
    { q: 'How many letters are in the English alphabet?', a: '26', w: ['24', '25', '28'] },
    { q: 'What currency is used in Japan?', a: 'Yen', w: ['Won', 'Yuan', 'Ringgit'] },
    { q: 'What currency is used in the United Kingdom?', a: 'Pound sterling', w: ['Euro', 'Dollar', 'Franc'] },
    { q: 'Which is the smallest country in the world?', a: 'Vatican City', w: ['Monaco', 'San Marino', 'Liechtenstein'] },
    { q: 'Which country has the city of Marrakesh?', a: 'Morocco', w: ['Tunisia', 'Egypt', 'Algeria'] },
    { q: 'Which city is known as the Big Apple?', a: 'New York', w: ['Chicago', 'Los Angeles', 'Boston'] },
    { q: 'The Colosseum is in which city?', a: 'Rome', w: ['Athens', 'Naples', 'Milan'] },
    { q: 'Which river flows through Paris?', a: 'Seine', w: ['Loire', 'Rhône', 'Thames'] },
    { q: 'Which river flows through Berlin?', a: 'Spree', w: ['Elbe', 'Rhine', 'Oder'] },
    { q: 'How many states does Germany have?', a: '16', w: ['12', '14', '18'] },
    { q: 'How many states does the USA have?', a: '50', w: ['48', '51', '52'] },
    { q: 'Which is the largest country by area?', a: 'Russia', w: ['Canada', 'China', 'USA'] },
    { q: 'What is the main language of Brazil?', a: 'Portuguese', w: ['Spanish', 'Brazilian', 'French'] },
    { q: 'Who developed the theory of relativity?', a: 'Albert Einstein', w: ['Isaac Newton', 'Niels Bohr', 'Stephen Hawking'] },
    { q: 'Who discovered penicillin?', a: 'Alexander Fleming', w: ['Louis Pasteur', 'Marie Curie', 'Robert Koch'] },
    { q: 'What is the most common blood type?', a: 'O positive', w: ['A positive', 'B negative', 'AB positive'] },
    { q: 'Which organ pumps blood through the body?', a: 'Heart', w: ['Liver', 'Lungs', 'Kidney'] },
    { q: 'What is the largest organ of the human body?', a: 'Skin', w: ['Liver', 'Brain', 'Lungs'] },
    { q: 'How many teeth does an adult human usually have?', a: '32', w: ['28', '30', '36'] },
    { q: 'Which colour do you get by mixing blue and yellow?', a: 'Green', w: ['Purple', 'Orange', 'Brown'] },
    { q: 'How many colours are in a rainbow (usual count)?', a: '7', w: ['5', '6', '8'] },
    { q: 'Which instrument has 88 keys?', a: 'Piano', w: ['Organ', 'Accordion', 'Harpsichord'] },
    { q: 'How many strings does a standard guitar have?', a: '6', w: ['4', '5', '7'] },
    { q: 'Which band sang "Bohemian Rhapsody"?', a: 'Queen', w: ['The Beatles', 'Led Zeppelin', 'ABBA'] },
    { q: 'From which country does the band ABBA come?', a: 'Sweden', w: ['Norway', 'Denmark', 'Finland'] },
    { q: 'Which superhero is also known as the Dark Knight?', a: 'Batman', w: ['Superman', 'Spider-Man', 'Iron Man'] },
    { q: 'What is the name of Harry Potter\'s owl?', a: 'Hedwig', w: ['Errol', 'Crookshanks', 'Scabbers'] },
    { q: 'In "The Lion King", what is the name of Simba\'s father?', a: 'Mufasa', w: ['Scar', 'Rafiki', 'Zazu'] },
    { q: 'Which is the smallest dog breed?', a: 'Chihuahua', w: ['Pug', 'Dachshund', 'Beagle'] },
    { q: 'Which dog breed was originally bred to hunt hares by scent?', a: 'Beagle', w: ['Poodle', 'Boxer', 'Husky'] }
];
